language: ruby
env:
- CODECLIMATE_REPO_TOKEN=90f4d5e08c45d89ca964759071583b186fe1af7f7a77a14a134d73db3b399dac
rvm:
- 2.1.5
before_install:
- sudo apt-get update -qq
before_script:
- psql -c 'create role pq login createdb;' -U postgres
addons:
postgresql: 9.3
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake db:seed
deploy:
  provider: heroku
  api_key:
    secure: UO652t0hADjMn97lsovMMsTNa08xBnTozTmDB1vr/7aD18Ut0kTYU2kq1Mv2QDCCNO3V3me+QozAx/SKPEVI80ZdegQHWt5sbjX/ZSOwy/ks6H7+a8rBeQbHhqzEwqN5WgGNFsioxLltsS5eqLnA7U3C2imRFlcTdRhB59LRHZ8=
  app: cb-anagram
  on:
    repo: CeeBeeUK/cb-anagram
