language: ruby
rvm:
- 2.1.5
before_install:
- sudo apt-get update -qq
deploy:
  provider: heroku
  api_key:
    secure: UO652t0hADjMn97lsovMMsTNa08xBnTozTmDB1vr/7aD18Ut0kTYU2kq1Mv2QDCCNO3V3me+QozAx/SKPEVI80ZdegQHWt5sbjX/ZSOwy/ks6H7+a8rBeQbHhqzEwqN5WgGNFsioxLltsS5eqLnA7U3C2imRFlcTdRhB59LRHZ8=
  app: cb-anagram
  on:
    repo: CeeBeeUK/cb-anagram
